### Update Patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Senibo Don-Pedro22wwii",
  "email": "t@gmail.com",
  "address": "Home",
  "dateOfBirth": "1999-02-08"
}

###
