### CREATES A NEW PATIENT ENTITY
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "JOHN DOE WITH BILLING ACCOUNT",
  "email": "TEST_BILLING_ACCOUNT3@example.com",
  "address": "123 main street",
  "dateOfBirth": "08-02-1999",
  "registeredDate": "05-10-2025"
}

###
